name: "master builds"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, macOS-10.14, windows-2016, ubuntu-18.04]
        os: [ubuntu-latest]
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v1

    - name: "npm update"
      run: npm upgrade node

    - name: install ncc
      run: npm i -g @vercel/ncc

    - name: "npm install"
      run: npm install

    - name: show package.lock
      run: cat package-lock.json

    - name: Does ncc exist
      run: which ncc

    - name: "npm run build"
      run: npm run build

    - name: "npm run test"
      run: npm run test

    - name: "install aws cli"
      uses: ohthepain/action-install-aws-cli@v0.2
