name: "master builds"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macOS-10.14, windows-2016, ubuntu-18.04]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-node@v4

    - name: Check Node Version
      run: node -v

    - name: Install ncc
      run: npm i -g @vercel/ncc

    - name: "npm install"
      run: npm install

    - name: "npm run build"
      run: npm run build

    # The tests don't work
    # - name: "npm run test"
    #   run: npm run test

    # - name: "install aws cli"
    #   uses: ohthepain/action-install-aws-cli@v0.4
    #   # All commands after this point have access to the AWS CLI
    # - run: aws s3 ls
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
